### ISSUE TITLE
Identify the difference between manual scheduling system and online scheduling system

### ISSUE THREAD

**Issue by JasperAmiel14** [IT3A-2016/XENO#16]

**Comment by ghost** [comment]
The manual scheduling system is the pen-and-paper method old way of scheduling appointments for an individual or work group, in which all scheduling is funneled through an appointments secretary with a central calendar. In this model, the people whose time is being booked must check in regularly to find out what their schedule is, and to let the secretary know what times are unavailable. Online scheduling systems are a method of using scheduling algorithms and rules to help multiple people manage appointments and meetings. Computerized scheduling allows users to publicly share free time on their calendars, while keeping specific appointments private. They tend to be more efficient than manual scheduling, but a good appointments secretary can more effectively handle some situations.
