### ISSUE TITLE
Storyboard of the website

### ISSUE THREAD

**Issue by JasperAmiel14** [IT3A-2016/XENO#17]

**Comment by ghost** [comment]
![image](https://zube.io/files/IT3A-2016/5eaf1d1b98673c7f43e2f399d25ade35.png)

![image](https://zube.io/files/IT3A-2016/537a16a3e74e6ef84f139c7da47dac47.png)

![image](https://zube.io/files/IT3A-2016/e6511cc6ddf25fd040892052a713e2ff.png)

![image](https://zube.io/files/IT3A-2016/8d669dae42508dc0337148879eef7e44.png)

![image](https://zube.io/files/IT3A-2016/e9780c11619ad01ff177669c63d2d8f0.png)

![image](https://zube.io/files/IT3A-2016/537a16a3e74e6ef84f139c7da47dac47.png)

![image](https://zube.io/files/IT3A-2016/e6511cc6ddf25fd040892052a713e2ff.png)

![image](https://zube.io/files/IT3A-2016/ccdcc2eb597958aa997378a8f6c14882.png)

![image](https://zube.io/files/IT3A-2016/9fa608cbaf10b1db3340005be5ba46d1.png)
