### ISSUE TITLE
Structure design of the system

### ISSUE THREAD

**Issue by JasperAmiel14** [IT3A-2016/XENO#18]

**Comment by torejacasey** [comment]
![image](https://zube.io/files/IT3A-2016/5d800abf2027ece22e1df0a91d715199.png)

**Comment by ghost** [comment]
![image](https://zube.io/files/IT3A-2016/83df5313c3320e417758cb86d8b97fa0.png)


![image](https://zube.io/files/IT3A-2016/88efb4ca44cf33f23803cfc93765eaea.png)
