### ISSUE TITLE
Putting Fields in the database for (student,counselor,report for violated sunctions,scheduling,sunctions, admin, and security)

### ISSUE THREAD

**Issue by JasperAmiel14** [IT3A-2016/XENO#8]

**Comment by dereck428** [comment]
![1.PNG](https://zube.io/files/IT3A-2016/15d1f650cdcdd2204af5fe22a87bf3d4.png)
![counselor.PNG](https://zube.io/files/IT3A-2016/3aa177aea130358aed9d40ee960c53cd.png)
![reportforsanctions.PNG](https://zube.io/files/IT3A-2016/e07033f0bc2c46be1c4326fa0e9f324a.png)
![scheduling.PNG](https://zube.io/files/IT3A-2016/4df267fab0a88e94d3d86fa62fa85597.png)
![security.PNG](https://zube.io/files/IT3A-2016/a06a63ae5336945b4826178050772b51.png)
![student.PNG](https://zube.io/files/IT3A-2016/4d3be5e0fd0bd3b445614c62fb6653a9.png)
![sunction.PNG](https://zube.io/files/IT3A-2016/d828cb92cee39182b1c2daf4e52448a5.png)
